#site

name: "Blog"
description: "Colorful"
#logo: 'assets/images/logo.png'
#favicon: 'assets/images/favicon.ico'
#baseurl: ''
disqus: "peterleeeeee-github-io"
#email: 'wowthemesnet@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  name: Peter
  site: https://peterleeeeee.github.io/
  avatar:
  bio: "newbie on Computer"
  email: dissgo12@gmail.com

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Peter
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

comments:
  provider: "disqus"
  disqus:
    shortname: "peter"

# Syntax
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "syntax"
highlighter: rouge

# Paginate
paginate: 10

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-172686009-1"
    anonymize_ip:

url: https://peterleeeeee.github.io/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
